<?php

module_load_include('inc', 'domain_black_list', 'includes/domain_black_list.menu');
module_load_include('inc', 'domain_black_list', 'includes/domain_black_list.entity');
module_load_include('inc', 'domain_black_list', 'includes/domain_black_list.permission');
module_load_include('inc', 'domain_black_list', 'includes/domain_black_list.forms');
module_load_include('inc', 'domain_black_list', 'includes/domain_black_list.theme');
module_load_include('inc', 'domain_black_list', 'includes/domain_black_list.preprocess');

/**
 * Example 1: Used for add post render callback.
 */
function domain_black_list_page_alter(&$page) {
  if (variable_get('domain_black_list_filter_html_page')) {
    $page['#post_render'][] = 'domain_black_list_page_alter_post_render';
  }
}

/**
 * Example 1: Clean all links that we have.
 */
function domain_black_list_page_alter_post_render($page) {
  $domains = DomainBlackList::getActives();

  if (!empty($domains)) {
    DomainBlackListFilter::formatDomains($domains);
    $count = DomainBlackListFilter::removeDomainsFromString($domains, $page);

    if (variable_get('domain_black_list_debug')) {
      $message = format_plural($count, t('1 domain was removed in the previous request ("Remove domains from HTML output").'),
        t('@count domains were removed in the previous request ("Remove domains from HTML output").'));
      DomainBlackListFilter::showDebugMessage($message);
    }
  }

  return $page;
}

/**
 * Example 2: Alter href attributes for links that used url().
 */
function domain_black_list_url_outbound_alter(&$path, &$options, $original_path) {
  if (variable_get('domain_black_list_alter_urls') && $options['external']) {
    $domains = DomainBlackList::getActives();

    if (!empty($domains)) {
      $path_domain_filtered = '';

      // Get the domain filtered. E.g: http://google.es -> googles.es
      DomainBlackList::isValid($path, $path_domain_filtered);

      if ($path_domain_filtered && in_array($path_domain_filtered, $domains)) {
        // @todo allow choose replace path in settings form
        $path = '<front>';
        $options['external'] = FALSE;

        $message = t('@domain has been removed in the current request from the href HTML attribute ("Remove url from link").', array('@domain' => $path_domain_filtered));
        DomainBlackListFilter::showDebugMessage($message);
      }
    }
  }
}

/**
 * Example 3: Validate fields for don't allow submit banned domains.
 */
function domain_black_list_field_attach_validate($entity_type, $entity, &$errors) {
  if (variable_get('domain_black_list_field_validation')) {
    // @todo save in array all errors and then format plural message
    $fields = DomainBlackListFilter::getValidateFieldsInstancesFromEntity($entity_type, $entity->type);
    $validate_fields_info = DomainBlackListFilter::getValidateFieldTypesInfo();
    $domains = DomainBlackList::getActives();

    if (!empty($domains)) {
      foreach ($fields as $field) {
        foreach ($entity->{$field->field_name} as $langcode => $items) {
          foreach ($items as $delta => $item) {
            foreach ($domains as $domain) {
              $domain_pattern = DomainBlackListFilter::getSimpleDomainPattern($domain);
              $properties = $validate_fields_info[$field->type]['properties_validation'];

              foreach ($properties as $property) {
                if (isset($item[$property]) && preg_match($domain_pattern, $item[$property])) {
                  $error = array(
                    'error' => $field->field_name,
                    'message' => t('The domain @domain is not allowed.', array('@domain' => $domain)),
                  );

                  if (isset($validate_fields_info[$field->type]['callback'])) {
                    call_user_func_array($validate_fields_info[$field->type]['callback'], array(&$error, $property));
                  }

                  $errors[$field->field_name][$langcode][$delta][] = $error;
                }
              }
            }
          }
        }
      }
    }
  }
}

/*
 * Example 4: Other option could be implements a filter for filtereds texts that
 *            transform the output removing invalid domains.
 * @todo
 */